-- ============================================================
-- NTANDA Cultural Heritage Site — Seed data
-- Run after schema + storage files.
-- ============================================================

-- ---------- Regalia (11) ----------
insert into public.regalia
  (title, tribe, category, description, full_details, image, era, material, origin_region, spiritual_significance, is_featured, slug)
values
  ($NT$Omukama's Crown$NT$, 'Batooro', 'Headwear',
   $NT$Circa 1890, symbol of sovereign authority and spiritual protection.$NT$,
   $NT$Handcrafted crown worn by the Omukama (King) of Tooro Kingdom during royal accession ceremonies. Adorned with intricate beadwork in royal gold, crimson, and ivory beads, passed down through sovereign generations.$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuBU1V0R0EcgLw1sZnnZN8-x2NBcTA62n10uL-nOgNA5E5xt_p5vpMEvMgSNu63pOqcBfJO0N5dzSlbID1Co44K_Xrkf1o6idI4ZP4wRLIZxBvXsOePdtMiAOHeA9cLCgwyslL5qDB8VzPFA9fitXFkDLiQO5wMybsG4fWtkrSw0ECaE19R9jzo4C8vHZDAJnySMh7HBWoHj3A2QOVdBd7wthb9mTBdYZ-mF6b8LS9xdI6KxU-KIJRUaLg$NT$,
   '19th Century', $NT$Glass beads, leather, velvet, brass wire$NT$, $NT$Tooro Kingdom, Western Uganda$NT$,
   $NT$Embodies the divine ancestral seal of the Omukama, protecting the nation from misfortune.$NT$, true, 'reg-omukama-crown'),
  ($NT$Brass Adornments$NT$, 'Ankole', 'Jewelry',
   $NT$Crafted symbols of wealth and social status from Western Uganda.$NT$,
   $NT$Heavy hand-poured brass bangles and neckpieces worn by noble Bahima women during weddings and royal gatherings. The shiny brass patina reflects sunlight across the pasture lands.$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuDoDprzjAh9EW1VKS7A9QFNiFOR8HFMlrhu8NDxRHpFYVI_LbMx0HLZyTCdpojUD4ias3OL2HYmBviPzBzMAq8PBXyBuKPduu8eyWigK25I5TMCzvhv-bqso9rhITSljysUMPcQRyROvXCkyqQZFGNwpBdHWYE_jEJoP3rLEOON8T7Hkb5MJxc4YkX72J3UBlb311V-00-6XnCfTBseIweXMOq1WwDrgYYj8pRrgnIwYf7683lGiKEcgA$NT$,
   'Late 19th Century', $NT$Poured brass, copper alloy, linen weave$NT$, $NT$Ankole Kingdom, South-Western Uganda$NT$,
   $NT$Bestows prosperity, blessing for herd fertility, and marital dignity.$NT$, true, 'reg-brass-adornments'),
  ($NT$Traditional Gomesi$NT$, 'Buganda', 'Garments',
   $NT$A ceremonial silk garment known for its elegant square neckline and sash.$NT$,
   $NT$The floor-length attire with iconic puffed shoulders and broad silk sash (Ekitambala). Worn across Central Uganda for official royal visits, Kwanjula introduction ceremonies, and state celebrations.$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuBuQ3mt3yKNbs8Ya41h0M-AY48rNc44B_u-qktGO6FnmQdgPs76jhgCLvlGxD9ts303xEvC_23sRpcTaA20USi1PEghwVNXfybebvwuaLITK-nJot505MbHpIZW8jBfUNZC56PK71bvkwkixfnGuLDKsr7mM5gjIM0DP4qCNUZfbOCzLSvZI1b3_rhh7NKEf0zgHvX8j5Jm3mLpViCd8e8EZsL0tsNVFm5zloLh9DFc9NMw66W1YT9MbQ$NT$,
   'Early 20th Century to Present', $NT$Woven silk, satin, cotton lining$NT$, $NT$Buganda Kingdom, Central Uganda$NT$,
   $NT$Represents feminine grace, cultural fidelity, and royal etiquette.$NT$, false, 'reg-traditional-gomesi'),
  ($NT$Enchoro Necklace$NT$, 'Maasai', 'Jewelry',
   $NT$Handcrafted glass beadwork representing age sets and social status.$NT$,
   $NT$Vibrant concentric beaded collar necklace woven with symbolic primary colors: red for bravery, blue for sky/rain, yellow for sun, and white for purity.$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuCx_hv7JsZzHRljsjKbBkeSnA6f896iQDBzpOxt80SyDGhiCbtHwTRUUod_jTifmzKyMrIh3tkBw4yWO0Arq8SWi3ooCngdPxoCZmp4aWH9UHenEHlcHXmbEqNs0_MVXJJL6pxw0duwBDHYlTf72bsAYXcbpEFGifd4ivltQ3wTCahr0_7M3qiUz8sjJLfomNw3iDtq1I_6qA79k7VKdesv_U5MqhqUsm6UtZ5PZELwlvgzg59oRcFzlw$NT$,
   'Mid 20th Century', $NT$Glass beads, sinew, recycled wire$NT$, $NT$East African Rift Valley$NT$,
   $NT$Identifies the wearer's age grade, marital standing, and clan lineage.$NT$, false, 'reg-enchoro-necklace'),
  ($NT$Ancestral Kanzu$NT$, 'Central Africa', 'Garments',
   $NT$The cream-colored tunics of dignity, often paired with a blazer.$NT$,
   $NT$The iconic traditional tunic worn by men across Buganda, Busoga, and Tooro. Features meticulous maroon embroidery (Omulela) running along the neck and collar line.$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuB18hazl_T9BRQ79LnPcNDhfZkQjiIY-aDvIsjHawGnnILVkPPYk_dXlo7hLspK0OvRWaWHk4h2-laDhCbjNEvNermiKELHSB_gXXywT4MtaQ5XzZmwkuYkVyOkgHJ5Tx71BLJuHpGZTt72WtpXJxKggjsCM1oHR0wQOMxwngDWsGcZTkNqh9Ht7VtL01Dagof3LNOPdWPSU8_W3lkNtdVneyanUY5bdIkeXPPY9pFFVow_3bcMYC7twQ$NT$,
   '19th Century', $NT$Fine linen, silk thread embroidery$NT$, $NT$Central Uganda & Great Lakes$NT$,
   $NT$Symbol of male statesman honor, integrity, and elder wisdom.$NT$, false, 'reg-ancestral-kanzu'),
  ($NT$Noopile Hat$NT$, 'Fulani', 'Headwear',
   $NT$A conical woven straw hat adorned with dyed leather and geometric patterns.$NT$,
   $NT$Protective and ceremonial conical hat woven from wild grasses and bound with hand-dyed dark red and brown leather strips.$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuAZkF4eeblK4ZE3VI6a-76D9gf8Q6-MqnlKgIQ0tFEh1nNZkUoKywen-BTdCSyjjFpOUgsPZumv9qUsK27yCxJHa_s5dtDcG6HMvCmE4HBiVAxNlt7UUga9-z29VPqebjXIR_SZOVGa3RXgkhXeoRKOc0_znnprn_KWFZaMlw2g1bo-pKgYLtksGvPslRYi7rBFmX-St0kDjnrPer8T9poWvLMyJj_DCLUkAxvCsSie7fYVnszBCpl_Yg$NT$,
   'Circa 1920', $NT$Natural grass straw, tanned goatskin leather$NT$, $NT$Sahel & Savanna Belt$NT$,
   $NT$Protects pastoral travelers under intense solar heat while symbolizing nomadic freedom.$NT$, false, 'reg-noopile-hat'),
  ($NT$Royal Kente$NT$, 'Asante', 'Garments',
   $NT$Hand-woven strips of silk and cotton with symbolic geometric motifs.$NT$,
   $NT$Master weaver cloth using traditional narrow-strip looms. Each geometric grid pattern encodes proverbs, royal history, and philosophical concepts.$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuDQADVp57HjA_KhXL6dxKKlgjZvh8evwWr1ymixFTo_AyVdWvJNT-t5nRHFkTpErQRHPrLNbMLfRIS3H5agpcR7rfS-Q5JedwpMLRIrrfa8WRsZQjpf5O2RLbN0HoDekcMqMT5TTgG5iDEFWb5S61LL2Xmp_aHpyYuCyDH0JShOjLeKG5gzjoIAjufzkdvfUoMgI0Cvp_I21oxjiGsMaFZQWMtZPeHb178AD4UoCOHZI2Tb28yD4jxBAQ$NT$,
   '18th Century Heritage', $NT$Pure silk thread, organic dyed cotton$NT$, $NT$West African Coast$NT$,
   $NT$Sacred garment reserved for paramount chiefs and life transition rituals.$NT$, false, 'reg-royal-kente'),
  ($NT$Agadez Cross$NT$, 'Tuareg', 'Jewelry',
   $NT$A silver talisman representing navigation and family lineage in the Sahara.$NT$,
   $NT$Lost-wax cast silver pendant incorporating the four cardinal directions and stellar constellation map points used by desert caravans.$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuC0YEbMS3vISYWHDhMg34vcutRROESXbg_njX6x-NV6uHlawIWJhaJYJb-n-B-7WLMus1nZFxSx1lZNTtydlz6UXd6Gd2r7jFGD7TOn8njR-uYU8r9lTNqFb8tTcR1kR3xD53HjgiI8_huZ78QzL6FC1l4LlglfTNzN6pIMwnQ9fOG-EGBmnaK_xevvdbxMPbzWS3OsOIFBKPT5JVuRpr6xtEcMGZxQX6FPiAdC2_PSvqwQ9GPA_i4aAw$NT$,
   '19th Century', $NT$Hand-chased pure silver, indigo linen thread$NT$, $NT$Saharan Highlands$NT$,
   $NT$Protective amulet passed from father to son upon reaching manhood.$NT$, false, 'reg-agadez-cross'),
  ($NT$Isicholo Headdress$NT$, 'Zulu', 'Headwear',
   $NT$A traditional flared hat representing maturity and social status.$NT$,
   $NT$Woven flared crown colored with natural red ochre pigments and structural woven grass. Worn exclusively by married women during ceremonial dances.$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuA3MgOXVnjN-7n8fUSMKiOj7H3c_K704qnsqSDzm0z_PUfkUIZlvI_mvSO9gh9E9dCw1aq0eFvkBszboI7ddXngSKNOVoH9TyibkKKpAoRoYLNv2AgBx9kgs2Ec1QgPkQoJaRBDh3ljT5LZNvG5A7Af6bYDg7TqWF82lePWyTEjVv_qfogd-OkarRgHmg9tgCVQTqksHWcMfHTLp5clOaQFH-nvw8LvYtYiBYaeYef1PKQKPaypAUsI8w$NT$,
   'Early 20th Century', $NT$Wild grass weave, red ochre pigment, cotton thread$NT$, $NT$Southern Africa$NT$,
   $NT$Demonstrates dignity, matronly wisdom, and commitment to hearth and family.$NT$, false, 'reg-isicholo-headdress'),
  ($NT$Ceremonial Beads$NT$, 'Acholi', 'Jewelry',
   $NT$Sacred ornamentation worn during cultural rites of passage.$NT$,
   $NT$Multi-stranded waist and neck beads crafted from carved bone, seeds, and semi-precious stone beads worn during harvest thanksgiving festivals.$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuBDMl-QoG1jHezoSYJ7rnKgRNtBO31TnXID9tG-tsPZLxZ7y5_cRmz8Co23d9_tNPobgMhczjqR8jZADVVZAc8EOfF1Uy5Hf_dGC0EnU46aJsKamWiV_DZ1Lge6D-X3SCpzISZyr4H0b3NiX12jwYwGioXwPoQMmOkwrT5qOc-R-ieXUpXQG-gjkzKj3tmvZdIX6p04uUknoFz2pixph4QNER140_c5DQ9HerTHrSOy-qjLNe9ySNOURA$NT$,
   '19th Century', $NT$Natural bone, polished seeds, stone, cowrie shells$NT$, $NT$Northern Uganda$NT$,
   $NT$Anchors youth to ancestral guidance during coming-of-age ceremonies.$NT$, false, 'reg-ceremonial-beads'),
  ($NT$Warrior Shield$NT$, 'Acholi', 'Ceremonial',
   $NT$Intricate hide patterns representing kinship and battle honors.$NT$,
   $NT$Crafted from seasoned buffalo hide with hand-forged iron reinforcements and brass wire bindings. Used in traditional royal guard ceremonies and ceremonial dance rituals (Larakaraka).$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuACKxHlWMB3LGLk5MiUPIa6G1-3B3LM8h7nqc49jeZaEC0WJGqyF3eq62wUbC6qPa_HAWBoB3Zdkj_fLh5TjyDawjZYEdPyEDGNvRsdV-8kSOUxXmsDOWJZYyRcH1FHofpeuXXtc3wl_b6iEUV24vJD7KjvNpW5lnxo5QpuY2mK79u-tSoZY5Se4rt2_-U8DUhMS07DtbZFoe1CHWE_jKKZZsdzPTgdYwC7uZrPsepp8DH7Sk4Wf84ovA$NT$,
   'Circa 1900', $NT$Cattle hide, hand-forged iron, wooden spine$NT$, $NT$Northern Region, Uganda$NT$,
   $NT$Carries clan crest markings signifying courage, defense of homesteads, and ancestral guardianship.$NT$, true, 'reg-warrior-shield');

-- ---------- Artifacts (7) ----------
insert into public.artifacts
  (title, culture, ref_number, estimated_age, location, image, description, material, added_time, significance_details, historical_context, audio_track, slug)
values
  ($NT$Royal Talking Drums (Atumpan)$NT$, 'Akan Heritage', '#NT-2042', 'Late 18th Century', 'Central Region, Ghana',
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuBuquU3ZFYnlBJiYIKUOW7gwG0EcIGKPleknvsKPQQy_RzaXygcKA7rl8ohs3MeXpkgI-Fvw7uEvZYv2D5niGGaHjQpLzrV_YSjDrhvSae72pyn1YEYBOR8EuRITxYoOVjTYgM7kZf6XAYvcA7a8_ACxts9zg6PHJULE-fLJi7dJbGxvWsasCy4mNm7gezGic1kGuqFPuZTtVvZg1QvWDYWmKcpeXlZXZwzR64K5-bZttTxem0mkiBW8g$NT$,
   $NT$Master pair of open goblet drums carved from a single hollowed log of Tweneboa wood, tuned with elephant hide and peg tensioners.$NT$,
   $NT$Polished hardwood, stretched hide, brass pegs, copper wire$NT$, 'ADDED 3 DAYS AGO',
   $NT$The Atumpan is the chief instrument for transmitting drum poetry, historical chronicles, and royal announcements across distances.$NT$,
   $NT$Played exclusively by master drummers (Kyerema) who were custodians of oral history and royal genealogies.$NT$,
   'talking_drums', 'art-talking-drums'),
  ($NT$Ancestral Vanguard Spears$NT$, 'Kongo Kingdom', '#NT-1088', 'Circa 1650 AD', 'Lower Congo River Basin',
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuCWPTnwWRgrx3YfTkcX0xI2JUEvSmbiB6LkxZLBxUeFEIktvOmGKWAOy_0-Q3i5vYxeHXpWG2ITzVPSYJDAztCwmc2faAxbZorhWBzEUqbEdVcN9j9JgnheCFwg6Yj0XQGdvW_HkHyqKSSn5qGF63_e-tZjJZUrty6kTQUwE25pihjjNouGVKO8MulGMHb_iUx_88j7y8kGujpxZ94p7R2NtsaBsx4dM6B4dggm3kp4dRHzHZTGEXsGUA$NT$,
   $NT$Forged iron spearheads with copper filigree spiral wraps along the shaft, preserved in court arsenals for ceremonial state marches.$NT$,
   $NT$Hand-forged iron, copper wire, African mahogany wood$NT$, 'ADDED 4 DAYS AGO',
   $NT$Emblematic of royal security, territorial sovereignty, and physical defense of clan boundaries.$NT$,
   $NT$Dating back to the height of the Kongo Kingdom, representing military discipline and blacksmithing mastery.$NT$,
   null, 'art-vanguard-spears'),
  ($NT$Terracotta Scholar Figure$NT$, 'Nok Culture', '#NT-0042', '500 BCE - 200 BCE', 'Kaduna State, Nigeria',
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuDK3NEGPCvDboXHozJYRPrYXg6Q01cszAn2T4evzKYpvTgybCf7jQ8am-xrNmyt_VY5kwzTuxa8QU4hMoNqavhK2FBxK4Zsqt5PVjKQ8n6TMPFiuTFJiNz2avFcOE4MtVaOXu1qEEwzvD4wFqxNAscocz6niqhENQ2UGXibhSW8wuolVGQTqFiX98LCYXLUHESst9kdsXHu7nz8LNIiZKvpIgwztGBqsyDCgN4nGKbBfcSJ2u4DYdQR4g$NT$,
   $NT$Ancient hollow terracotta head featuring characteristic oval eyes, pierced pupils, and highly elaborate braided coiffure.$NT$,
   $NT$High-fired iron-bearing clay, natural ochre slip$NT$, 'ADDED 1 WEEK AGO',
   $NT$One of the earliest known sculptural traditions in Sub-Saharan Africa, testifying to sophisticated early iron-age urban centers.$NT$,
   $NT$Uncovered during tin mining operations in Nok village, revealing sophisticated terracotta kiln firing techniques.$NT$,
   null, 'art-terracotta-figure'),
  ($NT$Golden Rhinoceros Ornament$NT$, 'Great Zimbabwe Era', '#NT-9003', '13th Century', 'Limpopo Valley, South Africa',
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuD5PnVhf5suoTHCBxJWp6KXiAc8yj1_k2yLzRAlo5tkClg8onkvxKSESJLqfoJJC9IARrnfgNgWMA_3bRKgOBz6MSwgmbPMIxPPSIpNQ1iMd3iRN_kplj3HKlwq7quJ6EbY4puUfz4v90V8ZpDBLJ8_ga8JeiS_AmN0lFIcNYPoKHKv7vmqSYsluHzbLngbb453UdAXqboWGHAmvW_xuB7Fd5rw--HlixkDssx_BMSPTNJVeyS8FfBl6A$NT$,
   $NT$Foil-hammered pure gold sheet wrapped over a carved wooden rhinoceros core with delicate gold tack fasteners.$NT$,
   $NT$Hammered gold foil, carved hardwood core, gold tacks$NT$, 'ADDED 2 WEEKS AGO',
   $NT$Symbol of monarchical power, solitary strength, and extensive trans-Indian Ocean gold trade routes.$NT$,
   $NT$Discovered at the royal burial site of Mapungubwe Hill, highlighting southern Africa's rich medieval gold civilization.$NT$,
   null, 'art-golden-rhino'),
  ($NT$Mbugu Tapestry$NT$, 'Baganda Heritage', '#NT-3011', 'Circa 1910', 'Central Uganda',
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuAueui5xZKaxJBJzp_Mp0MLFgmK51LdPf9U7mf3bUGOpxlfb7knWdFTPu1hyYb3A-_jfXXni0w_PkzS7DcWKnh0wogk8tLuJWnG50d_GZQDcbTQ4DkoKmgfB-UU5mHBpLjyB3W-ggAx65z0ZVMuLhzGi8hnwH9AyOsVnyo0aGgfgvatdhrzwsjwwWOqF0PkotSKyuT9-xNip66Z5HDhobHQOR_BnEwvLEK-tXu76nLVubwMzhmU4AK-Uw$NT$,
   $NT$Ritual barkcloth harvested from Mutuba trees (Ficus natalensis) and decorated with hand-stenciled organic charcoal patterns.$NT$,
   $NT$Hammered tree bark, natural charcoal & earth pigments$NT$, 'ADDED 2 DAYS AGO',
   $NT$Recognized by UNESCO as a Masterpiece of the Oral and Intangible Heritage of Humanity.$NT$,
   $NT$Barkcloth making in Buganda is an ancient craft performed by hereditary royal artisans of the Ngonge clan.$NT$,
   null, 'art-mbugu-tapestry'),
  ($NT$Communal Libation Bowl$NT$, 'Bakiga / Kigezi', '#NT-4105', 'Late 19th Century', 'Kigezi Highlands, South-Western Uganda',
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuA5AhtRpfyE6OQpb2-ApuXgxWG89UtOZ3hBR_BPRvxzvlmpXwXx49MoUKGVr7G9hY8nZ3T5VYt-fpBSnWzFP_s-sKH3x0sFZGkyS6QVDrIL916kae1-k2En_24TWZPD035eXLmZKfGwlGCKnnrv58FGsJTyJszNZjHNVYMJWdyMQPq5x_x_OWTGwOjKLlpC3Zc14AsYuyshbCEH2CJopRxJblGxTnU2LyCGanL1Yt9SlmNgpPRbP2Te5A$NT$,
   $NT$Hand-carved hardwood vessel from Kigezi used for pouring ancestral libations and communal sorghum beer share rites.$NT$,
   $NT$Carved African mahogany, beeswax seal$NT$, 'ADDED 5 DAYS AGO',
   $NT$Used during harvesting rites to pour the first drop of millet wine onto the earth in honor of clan elders.$NT$,
   $NT$Symbolizes communal unity, dispute resolution, and spiritual communion among highland clans.$NT$,
   null, 'art-communal-libation-bowl'),
  ($NT$Royal Ennanga$NT$, 'Buganda Kingdom', '#NT-5080', '19th Century', 'Court of Mutesa I, Kampala',
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuCsPYlKZhtxTcVs6_VlJViM7SZYdQvKQgcCCH9clzxoKx_HF1CTDgOyyYiwYFqfPWWQAesmq8C-DmF2__2PwH5u30tlYTGpfbhYahCW3MlKEam54UtayUcJSORW3DAIARZciHN1W9c-iQvEPmNQWWkg1A7n9EuESdF481JlPNxE0oEt9T3rU5oRKLGw3lroJq3aviDgVzbSh8i3cZuESpGYprWc7_lRx6Ux6sIWV4E-I01Q4mfxRj1XUQ$NT$,
   $NT$8-stringed royal harp curved from wood and resonant monitor lizard hide membrane, tuned to an pentatonic scale.$NT$,
   $NT$Resonant hardwood, monitor lizard skin, twisted fibre strings$NT$, 'ADDED 1 WEEK AGO',
   $NT$Played by court musicians to recount royal epics, heroic deeds of Kabakas, and moral allegories.$NT$,
   $NT$Restored instrument from the private collection of Kabaka Mutesa I of Buganda.$NT$,
   'ennanga_harp', 'art-royal-ennanga');

-- ---------- Communities (5) ----------
insert into public.communities
  (name, region, description, full_history, avatar_image, banner_image, population, language, royalty_leader, totems, key_traditions, slug)
values
  ('Baganda', 'Central Region',
   $NT$The largest ethnic group in Uganda, the Baganda belong to the Bantu-speaking people with a highly organized social and political system centered around the Kabaka (King). They are known for their deep-rooted traditions in barkcloth making, coffee farming, and vibrant oral literature.$NT$,
   $NT$The Kingdom of Buganda was founded in the 14th century by Kintu, the first Kabaka. Centered around the fertile shores of Lake Victoria, Buganda developed a sophisticated central administration, a naval fleet of war canoes, and a intricate clan system (Obwakabaka Bwa Buganda). Each clan maintains a specific hereditary role in the service of the Kabaka.$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuCiNYokRgq7b9Col4s_Fxk5K7D0nVQQ0DxfQ8hAEd6di69U2TU1iWXDySDvVuyJGoSfnzR1anN6XBqMXfhIq78k77F6PirKwEALBgLPSc6CCQxJnQhXaKTS7Ul3YiW4E4Y2RUjHMb1rqcHrnBRJ3Wp13zAVAOX_rjRaAc5W2yWroa7F5sn-EB9XKcW22RYlt0suRSKiyIh0rhy3onCe6KB96JwVpPhOwMrawC0poXXAd700OusQL8THSg$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuCbT5D5jXTv5V0NWNdHI8okG9Ap23F9ZeaZvyXkQQzvu0Ugi6tIZRnerf25LPYdLAdVBL_TyWXswXwXNfZpvO37LCFsURK_ccIams951-IVN6eCAn8OEreIMpeAMTQVuBtZEozKuDfMIWyHxeXtc05V5obWpcxWZVf9va6n7zVzOgXySCJ57NdAjyZ_jHgTaCnk8kxl2K47scwpbDYLdMpAz_J0bcGWeuGqAaoAfuRm74ScWbZtWp7VkQ$NT$,
   '7.5+ Million', 'Luganda', 'His Majesty Kabaka Ronald Muwenda Mutebi II',
   $json$[{"name":"Pangolin","symbol":"🦎","meaning":"Protector of hidden wisdom","description":"The prime clan responsible for royal architectural carpentry.","lugandaName":"Lugave"},{"name":"Sheep","symbol":"🐑","meaning":"Gentleness and peace","description":"Custodians of royal barkcloth crafting.","lugandaName":"Ndiga"},{"name":"Ant","symbol":"🐜","meaning":"Industrious collective strength","description":"Master builders and agricultural planners.","lugandaName":"Kinyomo"},{"name":"Lion","symbol":"🦁","meaning":"Sovereign courage","description":"Guardians of royal military defense.","lugandaName":"Mpologoma"}]$json$::jsonb,
   $json$["Barkcloth Harvesting (Olubugo)","Bakisimba Court Dance","Introduction Ceremony (Kwanjula)","Royal Drums (Mujaguzo)"]$json$::jsonb,
   'com-baganda'),
  ('Karamojong', 'North Eastern Region',
   $NT$A Nilotic ethnic group of nomadic agro-pastoralists living in the semi-arid Karamoja region. Their culture is centered around cattle, which represent wealth and status. Known for their intricate beadwork, traditional manyattas (homesteads), and the famous "Ekizino" jumping dance.$NT$,
   $NT$Originating from the Ateker cluster that migrated from the Ethiopian highlands in the 16th century, the Karamojong survived harsh climate conditions through nomadic cattle herding. Their social organization is governed by the Akiriket council of elders.$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuAg_XybGJ5cKK1WKdeZ5t7MnZVmbZEijn-DKoXvsHGroSP_YEHaexfDBa63Yi4NTas_8Pw-vGeyP2S64v-dqcxwX1p1RJXr0UTA98M7qJeyQ08G3PRXiXMf_v6iCkCgXEIzk9ukAxDRO-0JyNnpqr9EeMgeJ1ZNazSSeiZV1zZxP7aPrIJ0frTCYRPZ_k8uovmKZx1XaUgA3rBMynlLmBoyGXFZlAON8AJPzNkOBz6AQkCfGaiKFkdvlA$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuAERayqixLoyoO_cXP_lHnW1dWrQ1kt2zruMeNQm78Czv1qpJJHsdNh_92Dk48Zmby5xuvJiR3p_FPJMgQhcfS781SPxDviRGneros6lS9j3KA1b7TjYTUDT85khJfMNLg4P7dwDq8yagg4FKMK6BkIvggS9WluZYeAZsMIx5QKmbDcty41EO-exrrdI_2leI0UNus13lh4m2IUS9PckrXhT_AA9JvKopze7njxYRBazquNmYqJ0s6lDg$NT$,
   '1.2 Million', 'Nkaramojong', 'Council of Elders (Akiriket)',
   $json$[{"name":"Ostrich","symbol":"🦩","meaning":"Speed and vigilant sight","description":"Associated with swift messengers."},{"name":"Leopard","symbol":"🐆","meaning":"Silent bravery in wilderness","description":"Associated with elite warrior bands."}]$json$::jsonb,
   $json$["Ekizino High Jump Dance","Manyatta Homestead Building","Age-Set Initiation (Asapan)","Beaded Shuka Weaving"]$json$::jsonb,
   'com-karamojong'),
  ('Banyankole', 'Western Region',
   $NT$Inhabitants of the former Nkore kingdom, the Banyankole are divided into two groups: the pastoralist Bahima and the agriculturalist Bairu. They are world-renowned for the Ankole Long-horned cattle and their complex poetic recitations known as 'Ekyevugo'.$NT$,
   $NT$The Nkore Kingdom flourished in South-Western Uganda for centuries, built on pastoral economy and agricultural abundance. The Bahima pastoralists developed poetic arts celebrating the elegance of Ankole cattle, while Bairu agriculturalists cultivated rich banana plantations and ironcraft.$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuBFf8fB9tZeVD0dY2pku9AJn5IHl_hbYpzhqQnnU6Agf4v3R6FtlQ58-OUmyu5nc3TQhWUPHP9Yl_4bymGdlu1xO0HX0aMfvx2xSm7vQ9X2EVi0KL_yPS0eweEbWKPiqGk6tAsEef5oyPJFwQ2uhJ2gJKz7cRGtW0hEYZkcxGgNF7WrUrGZhi2zh-KNKUMF77rds6U8Nzt_gks0wV4aDSCQdwo_pkBK4Mf_Ma56aqGaPM8mElkEeP4L-Q$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuCtIgTMI38ld5oBEqMDpIMJN16Gyy53FWWcxhEcJEE4XijFsj8X5hdrx3d-JU0JyndfVLDKkB9qKD1frUJDWRtRxlqw1ZW0HqeNRZ3IKu167H9oWWNW49oQ8YtGgt8VmYjrx0f0UrtdZD3NSgkDLNJCCUjFAQa5A39BPkSmPsuY-ZWIXpVZUYoxSsAqTVm4Pk19IJV4XlSAGWUYE1itvEDruW2rDRjSXxZRltC-zDeMFSB1a0v-2fPv1g$NT$,
   '3.2 Million', 'Runyankole', 'Omugabe of Nkore Heritage Council',
   $json$[{"name":"Cattle","symbol":"🐂","meaning":"Life, sustenance, and beauty","description":"Sacred veneration of Inyambo cattle."},{"name":"Crested Crane","symbol":"🦩","meaning":"Grace and regal elegance","description":"Symbol of peace across Western pastures."}]$json$::jsonb,
   $json$["Ekyevugo Heroic Poetry","Kitaguriro Dance","Ekitambala Marriage Wraps","Ankole Cattle Sanctification"]$json$::jsonb,
   'com-banyankole'),
  ('Basoga', 'Eastern Region',
   $NT$Hailing from the Busoga sub-region between Lake Victoria and Lake Kyoga, the Basoga are a Bantu-speaking group with a rich monarchical history led by the Kyabazinga. They are masters of the 'Bigwala' gourd trumpet music, recognized by UNESCO as intangible heritage.$NT$,
   $NT$Busoga comprises 11 traditional chiefdoms unified under the ObwaKyabazinga Bwa Busoga. Located at the source of the River Nile in Jinja, Busoga culture is renowned for royal xylophone (Amadinda) music, Bigwala trumpet processions, and riverine spirituality.$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuDcyXgsr5md6TMl7gqqu1C6EMFV937WLEURq9Ht7yUPuRWGjqYkkfy_oplAeoMjNJviVYdaSmB3mO4Tgdixa5FBjeshutlhPnhNnMutpt59UNFCLETnrY2rmE2h-ELXxiLQCwgWZ7Yi1vRHn9xrz3LJJABJeADFBHW1e29qHqvI9uuu025-OUrhBjLI9RmDmgLHJnMdPHFN_vUl3SPY-4RtzFR9rNL3ZgJOyadW-P88_4l-9aSFSayQ$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuAwUMfmfZOokiicxhyVGgO_s-AJ-TJNXXcWam7ZcT6aYOkOHb_67bEm4ZBrMjI5eQ7p0d1MpkG1T1d1wxCQ9NCHjePkF5bH4DIG10_AUW2C6eCCrW7l7QYJ0lJQlhovLMiQ0qtkIJYbjsP6pWxmiA8G1fT7xjQ9B1rmtXv0NZSIJQjfKmSgTJ5aSWMJ8fWYlsfRG0RCC_dDy9b1Nd04r-cYLAU2vZ3jVHR8vxHTmRnncgVq_QgF6R2kdg$NT$,
   '3.8 Million', 'Lusoga', 'His Royal Highness Isebantu Kyabazinga William Gabula Nadiope IV',
   $json$[{"name":"Fish","symbol":"🐟","meaning":"Abundance of River Nile","description":"Guardians of river waterways and fishing lore."},{"name":"Otter","symbol":"🦦","meaning":"Agility and playfulness","description":"Associated with royal boatmen."}]$json$::jsonb,
   $json$["Bigwala Gourd Trumpet Orchestras","Nalufuka Dance","Jinja River Nile Blessings","Amadinda Giant Xylophone"]$json$::jsonb,
   'com-basoga'),
  ('Lugbara', 'North Western Region',
   $NT$A Central Sudanic ethnic group residing in West Nile (Arua, Maracha, Yumbe). Famous for their ancestor veneration structures (Ori), iron smelting heritage, and traditional harvest gastronomy like Otobi and Osu.$NT$,
   $NT$The Lugbara migrated from the South Sudan region centuries ago and settled in the fertile green highlands of West Nile. They maintained a decentralized democracy led by clan chiefs (Opi) and ritual rainmakers (Ezo).$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuBb34Fwj53nyQaZJ-v1J0Eo-scDXvRdZhb6FdcY0WVReaxK5RJPQzlVHKe0oe3f0X2AJ9jp2-aZxcF-lao1QVXOfqKzFe0M99w6NUDFgw3yRNTdQAJtPoEhAPkOcPlwILKzF5q3SmIBMJYZZCjv5PycJlmtYPWGU5wNIZMvHBlkvI6rnlECRg0wjlY0W08ZjpWaokx-4MigN9OQhgmtNWs04LrpYYcEMqramhLUbttiY4mvhzVCRmdyOQ$NT$,
   $NT$https://lh3.googleusercontent.com/aida-public/AB6AXuBb34Fwj53nyQaZJ-v1J0Eo-scDXvRdZhb6FdcY0WVReaxK5RJPQzlVHKe0oe3f0X2AJ9jp2-aZxcF-lao1QVXOfqKzFe0M99w6NUDFgw3yRNTdQAJtPoEhAPkOcPlwILKzF5q3SmIBMJYZZCjv5PycJlmtYPWGU5wNIZMvHBlkvI6rnlECRg0wjlY0W08ZjpWaokx-4MigN9OQhgmtNWs04LrpYYcEMqramhLUbttiY4mvhzVCRmdyOQ$NT$,
   '1.8 Million', 'Lugbarati', 'Agofe (Paramount Cultural Leader)',
   $json$[{"name":"Guineafowl","symbol":"🦤","meaning":"Vigilance and community flocking","description":"Symbol of peaceful coexistence."}]$json$::jsonb,
   $json$["Agwara Horn Dance","Ori Ancestor Shrine Rituals","Simsim & Honey Culinary Preservation"]$json$::jsonb,
   'com-lugbara');
